{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mqtt-explorer.secretName" . }}
  namespace: {{ include "mqtt-explorer.namespace" . }}
  labels:
    {{- include "mqtt-explorer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $value := .Values.secretEnv }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}
